$(document).ready(function(){
    $(".btnmenu").click(function(){
        $(".sidebar").toggleClass('closeside');
        $(".btnmenu").toggleClass('btnmenuclose');
        $("header").toggleClass('expand-main');
        $("#content").toggleClass('expand-main');
        $("body").toggleClass('overflow-hide');
    });
});

$(document).ready(function(){
    $(".refund").click(function(){
        $(".refund-box").css('display','block');
        $(".cancel-box").css('display','none');
        $(".refund").addClass('border');
        $(".cancel").removeClass('border');
    });
    $(".cancel").click(function(){
        $(".refund-box").css('display','none');
        $(".cancel-box").css('display','block');
        $(".cancel").addClass('border');
        $(".refund").removeClass('border');
    });
});